server:
  port: 8080

spring:
  application:
    name: gestion-poc-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gestion_poc}?sslmode=${DB_SSLMODE:prefer}
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD:app_password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug